version: '3.9'
services:
  server:
    network_mode: "host"
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/server
  client:
    network_mode: "host"
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/client
  sniffer:
    network_mode: "host"
    build:
      context: ./sniffer
      dockerfile: Dockerfile.dev
    volumes:
      - ./sniffer:/sniffer
