version: '3.9'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/server
    ports:
      - "12321:12321"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/client
  sniffer:
    build:
      context: ./sniffer
      dockerfile: Dockerfile.dev
    volumes:
      - ./sniffer:/sniffer
    depends_on:
      - client
      - server
